### PR TITLE
Impl Navbar and Hero lo-fi 

### LINKED ISSUE #23: Implement lo-fi Hero section for cmd-f

### PR DESCRIPTION
**Pull request by rmehri01**
# Description

Implemented lo-fi version of navbar and hero section.

Something I am unsure of:

- Should the navbar links to different parts of the page be hardcoded?

Fixes #23

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Tested locally with dev firebase
- [x] Works on staging site

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by yehee — COMMENTED** [review]
Thanks for putting all these together! Nothing stands out for me, though it might be hard to locate where the hamburger icon is. It seems like the button is there, but it's not visible to the user. Not sure if it's only happening locally, but I'm sharing a screenshot in case if you need it:
Screen Shot 2021-01-25 at 10 52 56 PM

**Review by yehee — APPROVED** [review]

**Comment by rmehri01** [comment]
@yehee Yeah this is happening for me too, it's because the icon is white and I didn't know what to do about it. Any thoughts? Also right now the navbar and apply button don't link to anything so should they be?

**Comment by yehee** [comment]
@rmehri01 Do you think those can be addressed when we work on the hi-fi version of it? If so, I think this PR should be good to go!

**Comment by rmehri01** [comment]
Alright sounds good then, thanks!

**Pull request merged**
