### PR TITLE
setup lh and lint

### PR DESCRIPTION
**Pull request by andykwan1124**
# Description

A pretty straightforward PR. A new workflow file is added that is triggered on all opened PRs. Includes linting and lighthouse checks.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Check out the PR checks below.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by kozr** [comment]
how did u get an emoji

**Comment by andykwan1124** [comment]
> how did u get an emoji

:construction_worker:

**Comment by andykwan1124** [comment]
:monocle_face: :monocle_face: :monocle_face: :monocle_face: 🧐

**Review by kozr — APPROVED** [review]
Should change to `yarn build:prod` once prod has sufficient data.

**Pull request merged**
